version: '3'

services:

  app:
    build: .
    volumes:
      - djangoproject:/djangoproject
      - static:/app/static
      - .db_data/db.sqlite3:/db.sqlite3
    ports:
      - "8000:8000"
    command: bash -c "python manage.py collectstatic --no-input && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"


volumes:
  djangoproject:
  static:
