# Generated by Django 4.2.11 on 2024-03-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_user_follow_user_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hash',
        ),
    ]
